apiVersion: batch/v1
kind: Job
metadata:
  name: estrazione-job
spec:
  template:
    spec:
      containers:
      - name: estratto
        image: ziofededocker/estrazionefile:latest
        command: ["python", "/app/estrazione.py"]
        env:
        - name: ENDPOINT
          value: ""
        - name: MINIO_ACCESS_KEY
          value: ""
        - name: MINIO_SECRET_KEY
          value: ""
        imagePullPolicy: IfNotPresent 
      restartPolicy: Never
      
  backoffLimit: 0



