apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jupyter-ingress
  labels: 
    app: jupyter-notebook
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: pippo.notebooks.kubernetes
      http:
        paths:
          - path: /
            backend:
              servicePort: 8888
              serviceName: jupyter-service2
